Task 1: Creating Arrays 
1. Write a Python program to:  
    o Create a 1D NumPy array of 10 integers ranging from 1 to 10. 
    o Create a 2D NumPy array of shape (3, 3) with integers from 1 to 9. 
    o Create a 3D NumPy array with random floating-point numbers of shape (3, 5, 3). 
2. Display the shape, size, and datatype of each array.

In [10]:
import numpy as np

In [11]:
a1 = np.arange(1,11)
print(a1)

[ 1  2  3  4  5  6  7  8  9 10]


In [12]:
print(a1.shape , a1.size , a1.ndim)

(10,) 10 1


In [13]:
a2 = np.arange(1,10).reshape(3,3)
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
print(a2.shape , a2.size , a2.ndim)

(3, 3) 9 2


In [15]:
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
a3 = np.random.rand(3,5,3)

In [17]:
a3

array([[[0.13255505, 0.88876278, 0.46093153],
        [0.45134818, 0.44160987, 0.8368039 ],
        [0.27384891, 0.3275432 , 0.96066941],
        [0.02726519, 0.37299775, 0.15931793],
        [0.27062416, 0.12001567, 0.88114832]],

       [[0.23107148, 0.87782175, 0.1916329 ],
        [0.76026807, 0.75858866, 0.88779498],
        [0.9294255 , 0.86856177, 0.27118805],
        [0.31444864, 0.82513263, 0.18697136],
        [0.31170092, 0.98409299, 0.74235051]],

       [[0.58735993, 0.01414603, 0.1567513 ],
        [0.58396972, 0.31096733, 0.33964101],
        [0.3909581 , 0.81663523, 0.39180021],
        [0.6199419 , 0.87961117, 0.4747494 ],
        [0.47461147, 0.38363582, 0.4732006 ]]])

In [18]:

print(a3.shape , a3.size , a3.ndim)

(3, 5, 3) 45 3


Task 2: Array Indexing and Slicing 
1. Create a NumPy array from the following list:  
data = [10, 20, 30, 40, 50, 60, 70, 80, 90] 
2. Write a Python program to:  
o Retrieve the first three elements of the array. 
o Retrieve every alternate element of the array. 
o Reverse the array. 
3. Perform the above operations and display the results. 

In [19]:
data = [10, 20, 30, 40, 50, 60, 70, 80, 90]
arr = np.array(data)

In [20]:
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [21]:
first3 = arr[:3]
first3

array([10, 20, 30])

In [22]:
first3 = arr[:3]
first3

array([10, 20, 30])

In [23]:
rev = arr[: : -1]
rev

array([90, 80, 70, 60, 50, 40, 30, 20, 10])

Task 3: Mathematical Operations 
1. Create two NumPy arrays, A and B, each with 5 random integers 
between 1 and 20. 
2. Write a Python program to:  
o Add, subtract, multiply, and divide the two arrays element
wise. 
o Compute the dot product of the arrays. 
o Find the mean, median, standard deviation, and variance of 
array A. 
o Identify the maximum and minimum values in array B and 
their indices. 

In [24]:
A = np.random.randint(1, 21, size=5)
B = np.random.randint(1, 21, size=5)

In [25]:
print(A)
print(B)

[19 17 19 17 15]
[19  4  1 14 17]


In [26]:
print('Addition : ',A+B)

Addition :  [38 21 20 31 32]


In [27]:
print('Subtraction : ',A-B)
print('Multiply : ',A*B)
print('Divide :',A/B)

Subtraction :  [ 0 13 18  3 -2]
Multiply :  [361  68  19 238 255]
Divide : [ 1.          4.25       19.          1.21428571  0.88235294]


In [28]:
dot = np.dot(A,B)
print("Dot Product = ",dot)

Dot Product =  941


In [29]:
print("Mean:", np.mean(A))
print("Median:", np.median(A))
print("Standard Deviation:", np.std(A))
print("Variance:", np.var(A))

Mean: 17.4
Median: 17.0
Standard Deviation: 1.4966629547095767
Variance: 2.24


In [30]:
max_val = np.max(B)
min_val = np.min(B)
max_idx = np.argmax(B)
min_idx = np.argmin(B)

In [31]:
print("Maximum Value:", max_val, "| Index:", max_idx)
print("Minimum Value:", min_val, "| Index:", min_idx)

Maximum Value: 19 | Index: 0
Minimum Value: 1 | Index: 2


Task 4: Reshaping and Transposing 
1. Create a 1D NumPy array of 12 integers ranging from 1 to 12. 
2. Write a Python program to:  
o Reshape the array into a 2D array of shape (4, 3). 
o Reshape the array into a 3D array of shape (2, 2, 3). 
o Transpose the reshaped 2D array and display its shape. 

In [32]:
array = np.arange(1,13)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [33]:
array_2d = array.reshape(4, 3)
array_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [34]:
array_3d = array.reshape(2, 2, 3)
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [35]:
transposed_2d = array_2d.T
print("Transpose of 2d array : ",transposed_2d)
print("Shape", transposed_2d.shape)

Transpose of 2d array :  [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
Shape (3, 4)


Task 5: Boolean Masking and Filtering 
1. Create a NumPy array with 15 random integers between 10 and 50. 
2. Write a Python program to:  
o Find all elements greater than 25. 
o Replace all elements less than 30 with 0. 
o Count the number of elements divisible by 5.

In [36]:
array = np.random.randint(10, 51, size=15)
array

array([29, 33, 30, 42, 48, 25, 23, 15, 29, 33, 11, 34, 12, 34, 22])

In [37]:
gt = array[array >25]
print("Greater then 25 :",gt)

Greater then 25 : [29 33 30 42 48 29 33 34 34]


In [38]:
mod = np.where(array<30,0,array)
print("Modified array",mod)

Modified array [ 0 33 30 42 48  0  0  0  0 33  0 34  0 34  0]


In [39]:
div = np.sum(array%5==0)
print("Number of elements divisible by 5:",div)

Number of elements divisible by 5: 3


Task 6: Working with Built-in Functions 
1. Use NumPy's built-in functions to:  
o Create an array of 10 equally spaced values between 0 and 1. 
o Create an identity matrix of size 4x4. 
o Generate a 1D array of 20 random integers between 1 and 100, 
sort it, and find the 5 largest elements. 

In [40]:

eq_spaced = np.linspace(0, 1, 10)
print("10 equally spaced values between 0 and 1 :", eq_spaced)

10 equally spaced values between 0 and 1 : [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [41]:
id_matrix = np.eye(4)
print("Identity matrix (4x4) :", id_matrix)

Identity matrix (4x4) : [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [42]:
ran_array = np.random.randint(1, 101, size=20)
print("Original Random Array :", ran_array)

Original Random Array : [  3   8  67  31  19  38  87  87 100  69  30  58  57  87  29  20  36  35
  76  37]


In [43]:
sorted = np.sort(ran_array)
five_large = sorted[-5:]
print("5 Largest Elements:", five_large)

5 Largest Elements: [ 76  87  87  87 100]


Task 7: Generic 
1. Create a Python program that:  
o Generates two large random arrays of size (100, 100). 
o Performs matrix multiplication on the two arrays. 
o Finds the determinant and inverse of the resulting matrix (if 
possible). 
o Measures the time taken to complete these operations. 

In [44]:
import time
A = np.random.rand(100, 100)
B = np.random.rand(100, 100)

In [45]:

start_time = time.time()
C = np.dot(A, B)
mult_time = time.time() - start_time
print("Matrix multiplication completed in {:.4f} seconds.".format(mult_time))
print(C)

Matrix multiplication completed in 0.0097 seconds.
[[25.61282515 22.00118506 24.32243089 ... 23.57930058 25.86241876
  21.29869465]
 [27.054425   22.4346036  27.96470983 ... 25.04875181 28.47779636
  25.04279615]
 [22.13148538 20.5133985  21.39765046 ... 21.23713522 23.36269919
  20.68986422]
 ...
 [25.78589968 23.38997146 26.46346652 ... 24.62020442 27.59016772
  22.78498566]
 [25.62899058 24.13017038 28.50623433 ... 25.80258519 27.34788802
  24.18292752]
 [22.9646397  20.47634507 23.21741275 ... 23.041136   23.2749328
  21.63654793]]


In [46]:
start_time = time.time()
det_C = np.linalg.det(C)
det_time = time.time() - start_time
print('Time Taken : ',det_time)
print("Determinant ; ",det_C) 

Time Taken :  0.0394740104675293
Determinant ;  -2.002914586470839e+51


In [47]:
if np.isclose(det_C, 0):
    print("Matrix is singular and cannot be inverted.")
else:
    start_time = time.time()
    inverse_C = np.linalg.inv(C)
    inv_time = time.time() - start_time
    print("Inverse computed in {:.4f} seconds.".format(inv_time))
    print(inverse_C)

Inverse computed in 0.0239 seconds.
[[ 0.75451496 -0.0340679   0.30419986 ... -0.13475261 -0.57550847
   0.90967178]
 [-0.88768732  0.00475893 -0.38205937 ... -0.02951586  1.09869005
  -1.0873218 ]
 [-0.42121188  2.30568444 -0.80497567 ... -2.61481047  0.20062463
   0.04986676]
 ...
 [ 1.94872195 -1.91508492 -0.17250915 ...  1.65397264 -1.50990096
   0.57186028]
 [ 0.64062333 -4.08443482  0.04699229 ...  4.3552219   0.22934888
  -0.39208434]
 [-1.31638835  1.79112406  0.10917324 ... -1.79769195  0.77166313
  -0.45949897]]
