# q1 . write your own coustom exception

In [2]:
class AgeTooSmallError(Exception):
    """Custom Exception: Raised when age is less than the required limit."""
    def __init__(self, message="Age is too small. Must be at least 18."):
        self.message = message
        super().__init__(self.message)


In [3]:


def check_age(age):
    if age < 18:
        raise AgeTooSmallError(f"Entered age {age} is too small!")
    else:
        print("Age is valid. You can proceed.")

In [4]:
try:
    user_age = int(input("Enter your age: "))
    check_age(user_age)
except AgeTooSmallError as e:
    print("Custom Exception Caught:", e)

Custom Exception Caught: Entered age 13 is too small!


In [5]:
# example 2
class MyCustomError(Exception):
    def __init__(self, message):
        super().__init__(message)
def divide_numbers(a, b):
    if b == 0:
        raise MyCustomError("Division by zero is not allowed.")
    return a / b
try:
    result = divide_numbers(10, 0)
    print("Result:", result)
except MyCustomError as e:
    print("Custom Exception Caught:", e)

Custom Exception Caught: Division by zero is not allowed.


QUESTION 2
Make a 2-d array and read and write it in a csv format.

In [6]:
import numpy as np
import csv

In [7]:
arr = np.array([[100, 200, 300],
                [400, 500, 600],
                [700, 800, 900]])

In [8]:

with open('array.csv', 'w', newline='') as f1:
    writer = csv.writer(f1)
    writer.writerows(arr)
print("Array written to 'array.csv'")

Array written to 'array.csv'


In [9]:
# Read array back from CSV
new_arr = []
with open('array.csv', 'r') as f1:
    reader = csv.reader(f1)
    for row in reader:
        new_arr.append([int(x) for x in row])

In [10]:
new_arr = np.array(new_arr)
print("Array read from 'my_array.csv':")
print(new_arr)

Array read from 'my_array.csv':
[[100 200 300]
 [400 500 600]
 [700 800 900]]
